DROP TABLE IF EXISTS commands;
DROP TABLE IF EXISTS ChessRoom;

CREATE TABLE commands (
    CommandID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Command VARCHAR(128) NOT NULL
);

CREATE TABLE ChessRoom (
    RoomID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    RoomName varchar(128) NOT NULL
);