package chess.dao;

import java.util.function.IntSupplier;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.support.KeyHolder;

public class Command {

    private final IntSupplier command;

    public Command(IntSupplier command) {
        this.command = command;
    }

    public void executeOrThrow(String exceptionMessage) {
        try {
            command.getAsInt();
        } catch (DataAccessException e) {
            throw new IllegalArgumentException(exceptionMessage);
        }
    }

    public static CommandResult execute(IntSupplier command) {
        return new CommandResult(command.getAsInt());
    }

    public static int extractAutoGeneratedId(KeyHolder keyHolder) {
        Number key = keyHolder.getKey();
        assert key != null;
        return key.intValue();
    }
}
